# Generated by Django 3.0.5 on 2021-04-05 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LikeTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_topicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Topic')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Write',
        ),
        migrations.AddField(
            model_name='likecomment',
            name='like_commentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comment'),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='topicid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Topic'),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
