# Generated by Django 2.2.12 on 2021-03-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210331_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='userid',
            new_name='user_name',
        ),
    ]
