# Generated by Django 3.0.5 on 2021-04-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210404_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
